sudo: required
dist: trusty

language: java
jdk:
- oraclejdk8
branches:
  only:
  - develop
  - master
cache:
  directories:
  - $HOME/.m2
notifications:
  email:
    recipients:
    - cedar-core-developers@lists.stanford.edu
    on_success: never
    on_failure: always
install: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn clean deploy --settings .m2/travis-settings.xml'
env:
  global:
  - secure: dEci6NEUZAfWQKCkHORGaDctBtY25scvHtwhmyPTtT4Dx1zEbXif0gmJlGvY8sQZmi/vpu3FxGIG76I9IYHWNF0QZ8ZOLFUkOOzhmfhRcYx991YzZCBmk/ZxEfsd1/bf1hIuuHHP/1Ja6B0t1iieevIgyT7lzroA1uRPFy2JL3SmZib2NoTGspXC5ymfIJ6w79GxNeq7+g0XLqR35xgB/mX+kxGvFiVfq3uVICnvurBhh056JGABK2AZXfqFzAEb7uxYUzQUc0XKYXl4oHYCSl8LEM1kB9o7gWz5XEQ1lODIXpeOLcq8ma0S/oqbK3tbOdYBDx1nlswky8XOgh38BySXmtQNpfmqXvPe+g0YxIX1mMRKeTa/VmE3TjtnmZE/nFNthn13eqRcJliFWbtOK4QEn1dvunyCcwEZcw/pCpntevfAkKnVEFySBqxLaOd1A/8L2o++zCZmYZLDO3gJziY4sukhM5h9Gn53HQDsc8GKe+NZTlCsmni5Ej6ymsMpSx+51Z5PXl6eWtfxYzjqhJVTXMRcv9ryFNtSAHCuukCw3/sBUwzg+HUEJbZQj6DAPI+coOVTzJJ8LA3gHpAk+kDlZFyzGUJnTuj3HHEPHQwJceToMwKrworlWwFVwpO/trx+EVNzgqn/ZVgOKErzDfQeqk2uuV2KSQ6g0Pq3STo=
  - secure: cR7Tll5NdNZ8cegKv2FBKOyqKSSo+rbA8KITaqb7j0T2zT8kd0m7u/sRws387viQ3l0XTDJ40kVCkXm+BVEY8pp9+HYScxFrM7PaxSwUchAG+tntbgH5B7AX2JkYl3tqDMB5C518qJCg9lanumDL1MO1MKL6PTORbWWxZMQqb1/YZs/ZiOGdM1bTrObvLo9y4cRwE43BO86BfkWsvDxLAHA27x4ntjb7FITjZuJM+O29kaRa5Kanxi6sGQGj7gkPiOLGlBYvQ9mZOf4dnpPg+DipzU9Whn0e6MHNBAG0/5JJmsy8tmao1lTls+bC5e/Sa7ei0castsqQuxguj6hTdEwa+BhFmtS179DrmdR1McTHxZoTUrG+pu3IjMgIAzWpVTAARATjM5tPTnCWppqy29l83UfW5TB0aElOe1QYTy5KsSAWotx6wjYVoKs/uLth2Xl4uCiJWB2b2DB1fDs45PDs6lINcxUcKVUkwrdUyutsZR8am9atO0HnEezycjaNpqDYdtGf59gk23METE/RannTYt7dwZeULgZnMHJzoV8sc/8vOcXRBs4LMxN9V+88BkfUKqZZb2dc8l+F7plhWBwUiiYBoxY9BMHxQIStQaynq9o9X65QiODlLwvF8M2UY8QAg6ohta6kP7goujVfYHKryl1t3PfcGYUjryH57co=
